POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Mastering React Hooks",
    "author":"Jane Smith",
    "url":"https://example.com/react-hooks-guide",
    "likes": 85
}